{{- if .Values.configMap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bookinfo-processor-config
  labels:
    app.kubernetes.io/name: bookinfo-processor
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ .Release.Name }}-bookinfo-processor
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
