apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bookinfo-processor
  labels:
    app: {{ .Release.Name }}-bookinfo-processor
    app.kubernetes.io/name: bookinfo-processor
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: bookinfo-processor
    app.kubernetes.io/instance: {{ .Release.Name }}
